name: Unity Test Runner

on: 
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  test:
    name: Run Unity Tests
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Run Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: ./ 
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        unityVersion: 2022.3.42f1
